### ISSUE TITLE
Config resetting 0.5.0 Alpha

### ISSUE THREAD

**Issue by WeasleyWalls** [BiggerSeries/Phosphophyllite#5]
Currently running both performant and Phosphophyllite on a server and tried using the config to disable the check. Currently Phosphophyllite reads the config but it then resets it so it only lasts for one restart.

**Comment by gizmocodes** [comment]
This has been fixed in the upcoming 0.4.5 and the next (not the current) 0.5 alpha. We haven't released a new alpha for 0.5 however, and aren't going to for a bit until some more issues with 0.5 are addressed. In the meantime, we would advise (as the warnings suggest) against using Performant. Thanks for the report!
